return {
  "folke/which-key.nvim",
  event = { "VeryLazy" },
  opts = {
    preset = "modern",
    delay = vim.o.timeoutlen,
    triggers = {
      { "<auto>", mode = "nixso" },
    },
    plugins = {
      marks = true,
      registers = true,
      spelling = {
        enabled = true,
        suggestions = 20,
      },
      presets = {
        motions = false,
        operators = false,
        text_objects = true,
        windows = true,
        nav = true,
        z = true,
        g = true,
      },
    },
    win = {
      border = "none",
      padding = { 1, 2 },
      wo = { winblend = 0 },
    },
    expand = 1,
    spec = {
      { "<leader>a", group = "AI Tools", icon = "🧠" },
      { "<leader>b", group = "Buffers", icon = "" },
      { "<leader>c", group = "Code & Commands", icon = "" },
      { "<leader>ck", group = "ScreenKey", icon = "" },
      { "<leader>f", group = "Files", icon = "" },
      { "<leader>g", group = "Git", icon = "󰊢" },
      { "<leader>l", group = "LSP", icon = "󱜙" },
      { "<leader>m", group = "Markdown Book", icon = "" },
      { "<leader>mb", group = "Book Indexes", icon = "" },
      { "<leader>mh", group = "Heading Levels", icon = "" },
      { "<leader>me", group = "Box Editor", icon = "" },
      { "<leader>mn", group = "Notes", icon = "" },
      { "<leader>md", group = "Header Lists", icon = "" },
      { "<leader>mw", group = "Wiki", icon = "" },
      { "<leader>ml", group = "Lore", icon = "" },
      { "<leader>mlc", group = "Characters", icon = "" },
      { "<leader>mla", group = "Abilities", icon = "" },
      { "<leader>mls", group = "Spells", icon = "" },
      { "<leader>mll", group = "Locations", icon = "" },
      { "<leader>mlo", group = "Organizations", icon = "" },
      { "<leader>mlr", group = "Rules", icon = "" },
      { "<leader>n", group = "Notifications", icon = "" },
      { "<leader>o", group = "Options", icon = "" },
      { "<leader>p", group = "Packages & Profiling", icon = "" },
      { "<leader>q", group = "Quit & Save", icon = "" },
      { "<leader>s", group = "Sessions", icon = "" },
      { "<leader>w", group = "Windows & Smart Splits", icon = "荒" },
      { "<leader>wt", group = "Tabs", icon = "荒" },
      { "<leader>x", group = "Diagnostics", icon = "" },
      { "<leader>y", group = "Yank", icon = "" },
    },
  },
}
